server:
    port: 8080

spring:
    application:
        name: auto-push

    # 数据库配置
    r2dbc:
        url: ${DB_URL:r2dbc:postgresql://localhost:5432/autopush}
        username: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:postgres}
        pool:
            enabled: true
            initial-size: 5
            max-size: 20

    # Flyway配置（用于数据库迁移）
    flyway:
        enabled: true
        locations: classpath:db/migration

    # 邮件配置
    mail:
        host: ${MAIL_HOST:smtp.example.com}
        port: ${MAIL_PORT:587}
        username: ${MAIL_USERNAME:your-email@example.com}
        password: ${MAIL_PASSWORD:your-password}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

# 日志配置
logging:
    level:
        root: INFO
        com.zhechengdata.autopush: DEBUG
        org.springframework.data.r2dbc: INFO
