server:
    port: 8080

spring:
    application:
        name: auto-push

    # 数据库配置
    r2dbc:
        pool:
            enabled: true
            initial-size: 5
            max-size: 20

    # Flyway配置（用于数据库迁移）
    flyway:
        # 禁用自动配置，使用我们自己的FlywayConfig类
        enabled: false
        # 不再需要在这里指定locations，由FlywayConfig自动检测
        # locations: classpath:db/migration/mysql,classpath:db/migration/postgresql
        validate-on-migrate: on
        clean-disabled: on
        url: ${spring.r2dbc.url}
        password: ${spring.r2dbc.password}
        default-schema: ${spring.jpa.properties.hibernate.default_schema}
        target: latest
        out-of-order: on


    profiles:
        include: mysql

# 日志配置
logging:
    level:
        root: info
        com.zhechengdata.autopush: DEBUG
        org.springframework.data.r2dbc: INFO
        org.flywaydb: INFO
